title: Git & GitHub Course
description: Learn Git & GitHub from Beginner to Advanced
theme: jekyll-theme-minimal
markdown: kramdown

# Optional: custom logo
logo: /assets/logo.png
show_downloads: false
