title: Git & GitHub Course
description: Learn Git & GitHub from beginner to advanced — clean & readable.
markdown: kramdown
theme: null
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
remote_theme: null
permalink: pretty
defaults:
  - scope:
      path: ""
    values:
      layout: default
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
