title: Git & GitHub Course
description: Minimal, focused learning path from beginner to advanced.
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
plugins:
  - jekyll-remote-theme
remote_theme: pages-themes/minimal@v0.2.0
