title: คอร์ส Git & GitHub
description: บทเรียนภาษาไทยตั้งแต่พื้นฐานจนถึงขั้นสูง (Beginner → Advanced)
markdown: kramdown
theme: null
permalink: pretty
defaults:
  - scope:
      path: ""
    values:
      layout: default
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
